ARG ALPINE_VERSION=3.23

# Builder stage
FROM alpine:${ALPINE_VERSION} as builder

# build dependencies
RUN apk add --no-cache \
  cargo \
  cargo-auditable \
  cargo-deny \
  rust-clippy \
  rustfmt \
  sccache \
  just \
  openssl-dev
  #mold \

RUN mkdir /root/.cargo && \
<<EOF cat >> /root/.cargo/config.toml
#[target.'cfg(target_os = "linux")']
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]
[build]
rustc-wrapper = "/usr/bin/sccache"
EOF

WORKDIR /app
